[package]
name = "sorb-rust"
version = "0.1.0"
authors = ["Shybert <25749775+Shybert@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
